# Generated by Django 5.2.9 on 2025-12-16 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название категории"),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Название должности"),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="Например: Москва, удалённо",
                        max_length=200,
                        verbose_name="Местоположение",
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full", "Полная занятость"),
                            ("part", "Частичная занятость"),
                            ("project", "Проектная работа"),
                            ("internship", "Стажировка"),
                            ("remote", "Удалённая работа"),
                            ("freelance", "Фриланс"),
                        ],
                        default="full",
                        max_length=20,
                        verbose_name="Тип занятости",
                    ),
                ),
                (
                    "salary_min",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Минимальная зарплата",
                        null=True,
                        verbose_name="Зарплата от",
                    ),
                ),
                (
                    "salary_max",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Максимальная зарплата",
                        null=True,
                        verbose_name="Зарплата до",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("RUB", "₽ Рубли"),
                            ("USD", "$ Доллары"),
                            ("EUR", "€ Евро"),
                            ("KZT", "₸ Тенге"),
                            ("BYN", "Br Белорусские рубли"),
                        ],
                        default="RUB",
                        max_length=3,
                        verbose_name="Валюта",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Опишите должностные обязанности",
                        verbose_name="Описание вакансии",
                    ),
                ),
                (
                    "requirements",
                    models.TextField(
                        blank=True,
                        help_text="Опыт работы, навыки, образование...",
                        verbose_name="Требования к кандидату",
                    ),
                ),
                (
                    "benefits",
                    models.TextField(
                        blank=True,
                        help_text="Условия работы, бонусы, льготы...",
                        verbose_name="Мы предлагаем",
                    ),
                ),
                (
                    "experience",
                    models.CharField(
                        choices=[
                            ("no", "Без опыта"),
                            ("junior", "Junior (до 1 года)"),
                            ("middle", "Middle (1-3 года)"),
                            ("senior", "Senior (3-5 лет)"),
                            ("lead", "Lead (более 5 лет)"),
                        ],
                        default="middle",
                        max_length=20,
                        verbose_name="Требуемый опыт",
                    ),
                ),
                (
                    "education",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("secondary", "Среднее"),
                            ("specialized", "Среднее специальное"),
                            ("incomplete_higher", "Неполное высшее"),
                            ("bachelor", "Бакалавр"),
                            ("master", "Магистр"),
                            ("phd", "Кандидат наук"),
                            ("doctor", "Доктор наук"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Образование",
                    ),
                ),
                (
                    "skills",
                    models.TextField(
                        blank=True,
                        help_text="Укажите ключевые навыки через запятую",
                        verbose_name="Ключевые навыки",
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Контактное лицо"
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Контактный email"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Контактный телефон"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Рекомендуемая"),
                ),
                (
                    "is_urgent",
                    models.BooleanField(default=False, verbose_name="Срочная"),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество просмотров"
                    ),
                ),
                (
                    "applications_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество откликов"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата публикации"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата истечения"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="employer.category",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacancies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Работодатель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вакансия",
                "verbose_name_plural": "Вакансии",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SavedVacancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата сохранения"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_vacancies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "vacancy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_by",
                        to="employer.vacancy",
                        verbose_name="Вакансия",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сохраненная вакансия",
                "verbose_name_plural": "Сохраненные вакансии",
            },
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cover_letter",
                    models.TextField(
                        blank=True, verbose_name="Сопроводительное письмо"
                    ),
                ),
                (
                    "resume_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="resumes/%Y/%m/%d/",
                        verbose_name="Файл резюме",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новый"),
                            ("reviewed", "Просмотрено"),
                            ("invited", "Приглашён на собеседование"),
                            ("rejected", "Отклонено"),
                            ("accepted", "Принято"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата отклика"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Соискатель",
                    ),
                ),
                (
                    "vacancy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="employer.vacancy",
                        verbose_name="Вакансия",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отклик",
                "verbose_name_plural": "Отклики",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="vacancy",
            index=models.Index(
                fields=["-created_at"], name="employer_va_created_9a30ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vacancy",
            index=models.Index(
                fields=["is_active"], name="employer_va_is_acti_7f7711_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vacancy",
            index=models.Index(
                fields=["employer"], name="employer_va_employe_fda047_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="savedvacancy",
            unique_together={("user", "vacancy")},
        ),
        migrations.AlterUniqueTogether(
            name="application",
            unique_together={("vacancy", "applicant")},
        ),
    ]
