# Generated by Django 5.2.9 on 2025-12-17 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employer", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vacancy",
            name="expires_at",
        ),
        migrations.RemoveField(
            model_name="vacancy",
            name="published_at",
        ),
    ]
