# Generated by Django 5.2.9 on 2025-12-15 19:45

import django.contrib.auth.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("first_name", models.CharField(max_length=50, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=50, verbose_name="Фамилия")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Телефон"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Город"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Страна"
                    ),
                ),
                (
                    "citizenship",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Гражданство",
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("job_seeker", "Соискатель"),
                            ("employer", "Работодатель"),
                        ],
                        max_length=20,
                        verbose_name="Тип аккаунта",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Желаемая должность",
                    ),
                ),
                (
                    "experience",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Опыт работы",
                    ),
                ),
                (
                    "skills",
                    models.TextField(
                        blank=True, null=True, verbose_name="Ключевые навыки"
                    ),
                ),
                (
                    "education",
                    models.TextField(blank=True, null=True, verbose_name="Образование"),
                ),
                (
                    "previous_work",
                    models.TextField(
                        blank=True, null=True, verbose_name="Ранее занимаемые должности"
                    ),
                ),
                (
                    "previous_positions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Список предыдущих должностей в формате JSON",
                        null=True,
                        verbose_name="Ранее занимаемые должности",
                    ),
                ),
                (
                    "about",
                    models.TextField(blank=True, null=True, verbose_name="О себе"),
                ),
                (
                    "employment_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("full", "Полная занятость"),
                            ("part", "Частичная занятость"),
                            ("project", "Проектная работа"),
                            ("volunteer", "Волонтерство"),
                            ("internship", "Стажировка"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Тип занятости",
                    ),
                ),
                (
                    "work_schedule",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("full_day", "Полный день"),
                            ("shift", "Сменный график"),
                            ("flexible", "Гибкий график"),
                            ("remote", "Удаленная работа"),
                            ("hybrid", "Гибридный формат"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="График работы",
                    ),
                ),
                (
                    "relocation_ready",
                    models.BooleanField(
                        default=False, verbose_name="Готовность к переезду"
                    ),
                ),
                (
                    "business_trips_ready",
                    models.BooleanField(
                        default=False, verbose_name="Готовность к командировкам"
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата рождения"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Мужской"),
                            ("female", "Женский"),
                            ("other", "Другой"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="Пол",
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("single", "Холост/Не замужем"),
                            ("married", "Женат/Замужем"),
                            ("divorced", "Разведен(а)"),
                            ("widowed", "Вдовец/Вдова"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Семейное положение",
                    ),
                ),
                (
                    "languages",
                    models.TextField(
                        blank=True, null=True, verbose_name="Иностранные языки"
                    ),
                ),
                (
                    "driving_license",
                    models.BooleanField(
                        default=False, verbose_name="Водительские права"
                    ),
                ),
                (
                    "driver_license_category",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Категория прав",
                    ),
                ),
                (
                    "achievements",
                    models.TextField(blank=True, null=True, verbose_name="Достижения"),
                ),
                (
                    "portfolio_link",
                    models.URLField(blank=True, null=True, verbose_name="Портфолио"),
                ),
                (
                    "github_url",
                    models.URLField(blank=True, null=True, verbose_name="GitHub"),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Название компании",
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Сфера деятельности",
                    ),
                ),
                (
                    "company_size",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Количество сотрудников",
                    ),
                ),
                (
                    "company_description",
                    models.TextField(blank=True, null=True, verbose_name="О компании"),
                ),
                (
                    "company_website",
                    models.URLField(
                        blank=True, null=True, verbose_name="Сайт компании"
                    ),
                ),
                (
                    "company_address",
                    models.TextField(
                        blank=True, null=True, verbose_name="Адрес компании"
                    ),
                ),
                (
                    "terms_accepted",
                    models.BooleanField(
                        default=False,
                        verbose_name="Согласие с пользовательским соглашением",
                    ),
                ),
                (
                    "newsletter",
                    models.BooleanField(
                        default=False, verbose_name="Подписка на рассылку"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль",
                "verbose_name_plural": "Профили",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
