# Generated by Django 5.2.9 on 2025-12-07 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=50, verbose_name="Фамилия")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("job_seeker", "Соискатель"),
                            ("employer", "Работодатель"),
                        ],
                        max_length=20,
                        verbose_name="Тип аккаунта",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Желаемая должность",
                    ),
                ),
                (
                    "experience",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Опыт работы",
                    ),
                ),
                (
                    "skills",
                    models.TextField(
                        blank=True, null=True, verbose_name="Ключевые навыки"
                    ),
                ),
                (
                    "education",
                    models.TextField(blank=True, null=True, verbose_name="Образование"),
                ),
                (
                    "previous_work",
                    models.TextField(
                        blank=True, null=True, verbose_name="Ранее занимаемые должности"
                    ),
                ),
                (
                    "about",
                    models.TextField(blank=True, null=True, verbose_name="О себе"),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Название компании",
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Сфера деятельности",
                    ),
                ),
                (
                    "company_size",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Количество сотрудников",
                    ),
                ),
                (
                    "company_description",
                    models.TextField(blank=True, null=True, verbose_name="О компании"),
                ),
                (
                    "terms_accepted",
                    models.BooleanField(
                        default=False,
                        verbose_name="Согласие с пользовательским соглашением",
                    ),
                ),
                (
                    "newsletter",
                    models.BooleanField(
                        default=False, verbose_name="Подписка на рассылку"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль",
                "verbose_name_plural": "Профили",
            },
        ),
    ]
