# Generated by Django 5.2.9 on 2025-12-16 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profileUser", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="previous_work",
        ),
    ]
