# Generated by Django 5.2.9 on 2025-12-18 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profileUser", "0002_remove_profile_previous_work"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="profile",
            managers=[],
        ),
    ]
