# Generated by Django 5.2.9 on 2025-12-18 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("responses", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="otklik",
            name="employer",
        ),
    ]
